name: Deploy Backend API

on:
  push:
    branches:
      - master
    paths:
      - 'api/**'  # Only triggers on changes inside the api folder

jobs:
  deploy_api:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [prod-ACTIVUM, prod-ALMAS]
    environment: ${{ matrix.environment }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Zip the API code (excluding .env and dev files)
      run: |
        cd api
        zip -r ../api_package.zip . \
          -x ".env" \
          -x "__pycache__/*" \
          -x "*.pyc" \
          -x ".gitignore"
        cd ..

    - name: Deploy to AWS Lambda
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ vars.AWS_REGION }}
        function_name: ${{ vars.LAMBDA_FUNCTION_API }}
        zip_file: api_package.zip